# Generated by Django 5.2.17 on 2026-09-29 20:22

import budget_manager.ledger.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_month",
                    models.DateField(
                        default=budget_manager.ledger.models.next_month_start,
                        help_text="The first month you budget for. Its transfers happen on the last day of the month before.",
                    ),
                ),
                ("nemkonto_min", models.BigIntegerField(default=0)),
                ("nemkonto_max", models.BigIntegerField(default=0)),
                ("nemkonto_opening", models.BigIntegerField(default=0)),
                ("general_savings_opening", models.BigIntegerField(default=0)),
                ("forecast_months", models.PositiveSmallIntegerField(default=24)),
            ],
            options={
                "verbose_name_plural": "budget settings",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="IncomeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "amount",
                    models.BigIntegerField(help_text="Expected amount each time it arrives."),
                ),
                ("interval_months", models.PositiveSmallIntegerField(default=1)),
                (
                    "first_month",
                    models.DateField(help_text="The first month this income is for."),
                ),
                ("end_month", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("nemkonto", "NemKonto"),
                            ("savings", "Savings (holds General Savings)"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("role", "nemkonto")),
                        fields=("role",),
                        name="one_nemkonto",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "savings")),
                        fields=("role",),
                        name="one_savings_account",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BalanceCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("nemkonto", "NemKonto"),
                            ("general_savings", "General Savings"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="Applies from the month-end after this month."),
                ),
                ("amount", models.BigIntegerField()),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("variable", "Variable")],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("interval_months", models.PositiveSmallIntegerField(default=1)),
                ("first_due", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("starting_balance", models.BigIntegerField(default=0)),
                (
                    "start_month",
                    models.DateField(
                        blank=True,
                        help_text="First month with a contribution. Empty: from the start.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="ledger.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="ledger.category",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MonthClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "In progress"), ("closed", "Closed")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(default=1)),
                ("done_accounts", models.JSONField(blank=True, default=list)),
                ("nemkonto_before", models.BigIntegerField(default=0)),
                ("income", models.BigIntegerField(default=0)),
                ("interest", models.BigIntegerField(default=0)),
                ("contributions", models.BigIntegerField(default=0)),
                ("nemkonto_after_transfers", models.BigIntegerField(default=0)),
                ("surplus", models.BigIntegerField(default=0)),
                ("taken", models.BigIntegerField(default=0)),
                ("nemkonto_end", models.BigIntegerField(default=0)),
                ("general_savings_before", models.BigIntegerField(default=0)),
                ("general_savings_after", models.BigIntegerField(default=0)),
                ("notices", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("contributions", models.BigIntegerField(default=0)),
                ("interest", models.BigIntegerField(default=0)),
                ("topups", models.BigIntegerField(default=0)),
                ("covers", models.BigIntegerField(default=0)),
                ("releases", models.BigIntegerField(default=0)),
                ("general_savings", models.BigIntegerField(default=0)),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="ledger.account",
                    ),
                ),
                (
                    "close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="ledger.monthclose",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["account__sort_order", "account_id"],
            },
        ),
        migrations.CreateModel(
            name="IncomeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("amount", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ledger.incomesource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("source", "month"), name="one_income_per_month")
                ],
            },
        ),
        migrations.CreateModel(
            name="InterestEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("amount", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest",
                        to="ledger.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "month"), name="one_interest_per_month"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cover", "Cover the NemKonto"),
                            ("release", "Move to General Savings"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="ledger.expense",
                    ),
                ),
                (
                    "close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="ledger.monthclose",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("close", "expense", "kind"), name="one_decision_each"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContributionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contribution", models.BigIntegerField(default=0)),
                ("expected_spend", models.BigIntegerField(default=0)),
                ("topup", models.BigIntegerField(default=0)),
                ("cover", models.BigIntegerField(default=0)),
                ("release", models.BigIntegerField(default=0)),
                ("balance_before", models.BigIntegerField(default=0)),
                ("planned_before", models.BigIntegerField(default=0)),
                ("amount_before", models.BigIntegerField(default=0)),
                ("amount_after", models.BigIntegerField(blank=True, null=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="ledger.expense",
                    ),
                ),
                (
                    "close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ledger.monthclose",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("close", "expense"), name="one_line_per_expense"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SpendingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("amount", models.BigIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spending",
                        to="ledger.expense",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("expense", "month"), name="one_spending_per_month"
                    )
                ],
            },
        ),
    ]
