# Generated by Django 5.2.17 on 2026-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_default_accounts_and_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cover", "Cover the NemKonto"),
                    ("release", "Move to General Savings"),
                    ("topup", "Top up from General Savings"),
                ],
                max_length=10,
            ),
        ),
    ]
