# Generated by Django 5.2.17 on 2026-10-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_decision_topup"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetsettings",
            name="opening_month",
            field=models.DateField(
                blank=True,
                help_text="Set when the budget is started mid-month: the month the starting balances refer to the start of.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="budgetsettings",
            name="started_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
