# Generated by Django 5.2.17 on 2026-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0004_budget_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributionline",
            name="funding",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="decision",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cover", "Cover the NemKonto"),
                    ("release", "Move to General Savings"),
                    ("topup", "Top up from General Savings"),
                    ("fund", "Fill a new expense from General Savings"),
                ],
                max_length=10,
            ),
        ),
    ]
