# Generated by Django 5.2.17 on 2026-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0009_budget_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed"),
                    ("variable", "Variable"),
                    ("running", "Running"),
                ],
                default="fixed",
                max_length=10,
            ),
        ),
    ]
