# Generated by Django 5.2.17 on 2026-10-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0010_expense_running"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="everyday_spending",
            field=models.BigIntegerField(
                default=0,
                help_text="Expected spending from the NemKonto itself in a month, for the forecast.",
            ),
        ),
        migrations.AddField(
            model_name="monthclose",
            name="nemkonto_spent",
            field=models.BigIntegerField(
                blank=True,
                help_text="Spent from the NemKonto itself since the last month-end; empty until entered.",
                null=True,
            ),
        ),
    ]
