# Generated by Django 5.2.17 on 2026-10-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0011_nemkonto_spending"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="first_amount",
            field=models.BigIntegerField(
                blank=True,
                help_text="The payment on the first due date, when it is a different amount (for example one that covers two months). Empty: the normal amount.",
                null=True,
            ),
        ),
    ]
