[project]
name = "budget-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "simonrydder" }]
requires-python = ">=3.12"
dependencies = [
    "pendulum>=3.1.0",
]

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[project.scripts]
budget-manager = "budget_manager:main"

[build-system]
requires = ["uv_build>=0.8.1,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.8.3",
    "freezegun>=1.5.5",
    "pytest>=8.4.1",
    "ruff>=0.12.4",
]
